# change prefix key to C-a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

set-option -g history-limit 10000
set-option -g default-terminal "screen-256color"
set-option -g escape-time 0

bind-key b set status
bind-key = setw synchronize-panes
bind-key S choose-session
bind-key a last-pane

# vim-like copy and paste
bind-key C-p run "@pasteCommand@ | tmux load-buffer - ; tmux paste-buffer"
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "@copyCommand@"
bind-key -T copy-mode-vi Enter send -X cancel

# This tmux statusbar config was created by tmuxline.vim
# on Mon, 13 Nov 2017


set -g message-command-style bg=colour11,fg=colour7
set -g message-style fg=colour7
set -g pane-active-border-style fg=colour4
set -g pane-border-style fg=colour11
set -g status "on"
set -g status-style none
set -g status-bg "colour10"
set -g status-justify "centre"
set -g status-left-style none
set -g status-left-length "100"
set -g status-right-style none
set -g status-right-length "100"
setw -g window-status-style fg=colour7,none
setw -g window-status-activity-style bg=colour10,none,fg=colour4
setw -g window-status-separator ""
setw -g window-status-style bg=colour10
set -g status-left "#[fg=colour10,bg=colour4,bold] #S #[fg=colour4,bg=colour11,nobold,nounderscore,noitalics]#[fg=colour7,bg=colour11] #F #[fg=colour11,bg=colour10,nobold,nounderscore,noitalics]#[fg=colour7,bg=colour10] #W #[fg=colour10,bg=colour10,nobold,nounderscore,noitalics]"
set -g status-right "#[fg=colour10,bg=colour10,nobold,nounderscore,noitalics]#[fg=colour7,bg=colour10] %a #[fg=colour11,bg=colour10,nobold,nounderscore,noitalics]#[fg=colour7,bg=colour11] %b %d | %R #[fg=colour4,bg=colour11,nobold,nounderscore,noitalics]#[fg=colour10,bg=colour4] #H "
setw -g window-status-format "#[fg=colour10,bg=colour10,nobold,nounderscore,noitalics]#[default] #I | #W #[fg=colour10,bg=colour10,nobold,nounderscore,noitalics]"
setw -g window-status-current-format "#[fg=colour10,bg=colour11,nobold,nounderscore,noitalics]#[fg=colour7,bg=colour11] #I | #W #[fg=colour11,bg=colour10,nobold,nounderscore,noitalics]"

# $Id: vim-keys.conf,v 1.2 2010-09-18 09:36:15 nicm Exp $
#
# vim-keys.conf, v1.2 2010/09/12
#
# By Daniel Thau.  Public domain.
#
# This configuration file binds many vi- and vim-like bindings to the
# appropriate tmux key bindings.  Note that for many key bindings there is no
# tmux analogue.  This is intended for tmux 1.3, which handles pane selection
# differently from the previous versions

# split windows like vim
# vim's definition of a horizontal/vertical split is reversed from tmux's
bind s split-window -v
bind v split-window -h

# move around panes with hjkl, as one would in vim after pressing ctrl-w
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# resize panes like vim
# feel free to change the "1" to however many lines you want to resize by, only
# one at a time can be slow
bind < resize-pane -L 1
bind > resize-pane -R 1
bind - resize-pane -D 1
bind + resize-pane -U 1

# bind : to command-prompt like vim
# this is the default in tmux already
bind : command-prompt

# vi-style controls for copy mode
setw -g mode-keys vi
