# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.extraModulePackages = [];
  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "uas"
    "sd_mod"
    "aesni_intel"
    "cryptd"
  ];
  boot.initrd.kernelModules = ["dm-snapshot"];
  boot.initrd.luks.devices."root-crypt" = {
    device = "/dev/disk/by-uuid/fc02466e-e37e-4965-a2f3-80302b2b9a21";
  };
  boot.kernelModules = ["kvm-intel"];

  environment.etc."crypttab".text = ''
    luks_exthd_a UUID=1ae179bf-23ae-4ee1-a839-01cf3800583a /etc/secrets/luks-keys/exthd-crypt luks,noauto
    luks_exthd_b UUID=3d7e2725-9a7d-42a9-824f-8515402788a4 /etc/secrets/luks-keys/exthd-crypt luks,noauto
  '';

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/4f7b47fa-cc1d-48bf-99de-deae23189c52";
      fsType = "ext4";
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/AF32-3F06";
      fsType = "vfat";
    };

    "/media/exthd-a" = {
      device = "/dev/mapper/luks_exthd_a";
      fsType = "ext4";
      options = [
        "noauto"
        "x-systemd.requires=systemd-cryptsetup@luks_exthd_a.service"
      ];
    };

    "/media/exthd-b" = {
      device = "/dev/mapper/luks_exthd_b";
      fsType = "ext4";
      options = [
        "noauto"
        "x-systemd.requires=systemd-cryptsetup@luks_exthd_b.service"
      ];
    };
  };

  swapDevices = [];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

  services.udev.extraRules = ''
    # external hard drives
    ACTION=="add", ENV{ID_FS_UUID}=="1ae179bf-23ae-4ee1-a839-01cf3800583a", ENV{SYSTEMD_WANTS}="media-exthd\\x2da.mount"
    ACTION=="add", ENV{ID_FS_UUID}=="3d7e2725-9a7d-42a9-824f-8515402788a4", ENV{SYSTEMD_WANTS}="media-exthd\\x2db.mount"
  '';
}
