# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.extraModulePackages = [];
  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "uas" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.initrd.luks.devices."root-crypt".device = "/dev/disk/by-uuid/0063beb1-5c4a-498f-894f-3602e3e3301a";
  boot.kernelModules = ["kvm-intel"];

  environment.etc."crypttab".text = ''
    luks_exthd_a UUID=1ae179bf-23ae-4ee1-a839-01cf3800583a /etc/secrets/luks-keys/exthd-crypt luks,noauto
    luks_exthd_b UUID=3d7e2725-9a7d-42a9-824f-8515402788a4 /etc/secrets/luks-keys/exthd-crypt luks,noauto
  '';

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/1ecb90b3-e9e9-4325-9f06-179e92d9788e";
      fsType = "ext4";
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/E769-426B";
      fsType = "vfat";
    };

    "/media/exthd-a" = {
      device = "/dev/mapper/luks_exthd_a";
      fsType = "ext4";
      options = [
        "noauto"
        "x-systemd.requires=systemd-cryptsetup@luks_exthd_a.service"
      ];
    };

    "/media/exthd-b" = {
      device = "/dev/mapper/luks_exthd_b";
      fsType = "ext4";
      options = [
        "noauto"
        "x-systemd.requires=systemd-cryptsetup@luks_exthd_b.service"
      ];
    };
  };

  swapDevices = [];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

  services.udev.extraRules = ''
    # external hard drives
    ACTION=="add", ENV{ID_FS_UUID}=="1ae179bf-23ae-4ee1-a839-01cf3800583a", ENV{SYSTEMD_WANTS}="media-exthd\\x2da.mount"
    ACTION=="add", ENV{ID_FS_UUID}=="3d7e2725-9a7d-42a9-824f-8515402788a4", ENV{SYSTEMD_WANTS}="media-exthd\\x2db.mount"
  '';
}
