# output=<not set>
font=Hack Nerd Font
# dpi-aware=auto
# use-bold=no
message="launch app"
prompt="❯ "
match-counter=yes
width=80
horizontal-pad=20

[colors]
background=1f1f28ff
text=a39f8eff
message=595956ff
prompt=839f60ff
placeholder=595956ff
input=a39f8eff
match=ff5d62ff
selection=363646ff
selection-text=cfb17cff
selection-match=ff5d62ff
counter=595956ff
border=7e9cd8ff

[border]
width=2
radius=5
